spring.application.name=LearningSB
server.port=8080

spring.datasource.url=jbdc:h2:mem:tododb
spring.datasource.driverclassname=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234

spring.h2.console.enabled=true